add_rules("mode.release", "mode.debug")
target("perecover")
    set_arch("x64")
    --set_optimize("fastest")
    set_kind("binary")
    set_languages("c++23")
    set_symbols("debug")
    add_files("src/*.cpp")
	add_includedirs("vendor/idasdk91/include")
	add_includedirs("vendor/linux-pe/includes")
    add_links("vendor/idasdk91/lib/x64_win_vc_64/*.lib")
    add_defines("__EA64__")